### ISSUE TITLE
About Jason

### ISSUE THREAD

**Issue by keslavi** [keslavi/HHMedia#12]
Add to 2012 on timeline….Board Director and Botanist for a biopharmaceutical company that did research under NIH on the 6630507 patient.

**Comment by keslavi** [comment]
-Chris
"_Do you want to add the name of the company?_"

**Comment by vinespn** [comment]
Added to 2012 on timeline….Board Director and Botanist for a biopharmaceutical company that did research under NIH on the 6630507 patient.

**Comment by HCranford** [comment]
complete
