### ISSUE TITLE
Retailer Sign-up

### ISSUE THREAD

**Issue by keslavi** [keslavi/HHMedia#16]
Direct all of these inquires to wholesale@haleighshope.com

**Comment by keslavi** [comment]
-Chris
"_We can send the forms there.  I saw your follow up that you wanted the tab removed completely.  Again, wouldn’t it be better to leave it up and then just drive sign-ups on the old site?  Or perhaps just have the link prepopulate an email to the wholesale email address?_"

**Comment by vinespn** [comment]
Retailer Sign-up inquires will send to wholesale@haleighshope.com

**Comment by HCranford** [comment]
complete
