### ISSUE TITLE
FAQ is hh Legal in my state

### ISSUE THREAD

**Issue by keslavi** [keslavi/HHMedia#19]
O	Under Is Haleigh’s Hope® legal in my state?...remove Canada and the 2nd Spain, add Luxembourg and Norway

**Comment by vinespn** [comment]
Under "Is Haleigh’s Hope® legal in my state?", Canada and the 2nd Spain has been removed. Luxembourg and Norway has been added.

**Comment by HCranford** [comment]
complete
