### ISSUE TITLE
Remove My Account and Shopping cart at the top of all screens.

### ISSUE THREAD

**Issue by keslavi** [keslavi/HHMedia#2]
My Account and Shopping cart points to the HH Merch site. I know it's a legal thing, but is this really different than a link to products?

**Comment by vinespn** [comment]
My Account and Shopping cart has been removed from the top of all screens on staging site.
http://haleighshopeme.staging.wpengine.com

**Comment by HCranford** [comment]
complete

**Comment by HCranford** [comment]
Complete, please close this ticket
