### ISSUE TITLE
faq: flowering hope relationship

### ISSUE THREAD

**Issue by keslavi** [keslavi/HHMedia#20]
Under What is the Flowering Hope Foundation? What is their association with Haleigh’s Hope®?....add email floweringhopefoundation@gmail.com

**Comment by vinespn** [comment]
Under "What is the Flowering Hope Foundation? What is their association with Haleigh’s Hope®?", email floweringhopefoundation@gmail.com has been added

**Comment by HCranford** [comment]
To get more information, donate, or become a member, visit the Flowering Hope Foundation, email them at floweringhopefoundation@gmail.com, or call them at (719) 368-7963.

Change to:
To get more information, donate, or become a member, visit www.floweringhope.co, email them at floweringhopefoundation@gmail.com, or call them at (719) 368-7963.

**Comment by vinespn** [comment]
To get more information, donate, or become a member, visit the Flowering Hope Foundation, email them at floweringhopefoundation@gmail.com, or call them at (719) 368-7963.

has been changef to:

To get more information, donate, or become a member, visit www.floweringhope.co, email them at floweringhopefoundation@gmail.com, or call them at (719) 368-7963.

**Comment by keslavi** [comment]
can someone re-verify this? I don't see it in faqs in staging or prod

**Comment by bermanc76** [comment]
I have verified that this has been changed and is correct on the live site.  Can someone please flag this as complete?

**Comment by HCranford** [comment]
Can we make one small change to the email address? Jason prefers to use info@floweringhope.co as the primary contact email.

Change to:
To get more information, donate, or become a member, visit www.floweringhope.co, email them at info@floweringhope.co, or call them at (719) 368-7963.

**Comment by bermanc76** [comment]
No problem.  Steve - are you able to just change this yourself in WordPress or do we need to wait for Alvin?

**Comment by keslavi** [comment]
completed, moved to prod
