### ISSUE TITLE
faq: remove when will my order ship

### ISSUE THREAD

**Issue by keslavi** [keslavi/HHMedia#23]
Remove When will my order ship?

**Comment by vinespn** [comment]
Removed "When will my order ship?" from FAQs page

**Comment by HCranford** [comment]
complete

**Comment by keslavi** [comment]
ok, i'm a little confused, I merged staging to prod, but I don't see the FAQS changes on staging. "When will my order ship" is still on at: 
http://haleighshopeme.staging.wpengine.com/faqs/

was this done in staging or prod?
not commenting on other FAQ changes but a request to add a section isn't there either.

**Comment by keslavi** [comment]
this was done in prod rather than staging. restored backup and verified complete.
