### ISSUE TITLE
faq: add I have questions about how to use the product

### ISSUE THREAD

**Issue by keslavi** [keslavi/HHMedia#24]
Add I have questions about how to use the product

Haleighs Hope works closely with the Flowering H.O.P.E. Foundation to offer education and support to individuals and families using the Haleighs Hope product line. If you would like more information on how others use Haleighs Hope, please call 719-368-7963 or emailfloweringhope@gmail.com add space after email and change email to floweringhopefoundation@gmail.com

**Comment by vinespn** [comment]
Added "I have questions about how to use the product" in FAQs page

**Comment by HCranford** [comment]
complete

**Comment by keslavi** [comment]
this was done in prod; it should have been done in staging. restored from backup and verified it was complete in prod
