### ISSUE TITLE
remove... My Account, Customer Support, Shipping & Return Policy, Terms of Use, Privacy Policy, and Products 

### ISSUE THREAD

**Issue by HCranford** [keslavi/HHMedia#25]
These are associated with the purchase of the product and should be on the ordering website, not the media site

**Comment by vinespn** [comment]
My Account, Customer Support, Shipping & Return Policy, Terms of Use, Privacy Policy, and Products has been removed from footer section on staging site.

http://haleighshopeme.staging.wpengine.com/

Updated file:
/wp-content/themes/haleighs-hope/footer.php

**Comment by bermanc76** [comment]
Heather - I have confirmed that these changes have been completed on the staging site.  Can you please also confirm (http://haleighshopeme.staging.wpengine.com/) and let Steve know that we can close this out?

**Comment by HCranford** [comment]
Yes, this is Complete

**Comment by keslavi** [comment]
moved to prod
