### ISSUE TITLE
Add Share This to blog and learn article pages on Media site

### ISSUE THREAD

**Issue by bermanc76** [keslavi/HHMedia#28]
Alvin - Please stack it vertically on the left hand side as discussed.

**Comment by vinespn** [comment]
Share This buttons have been added to blog and learn article pages on Media staging site. Stacked it vertically on the left hand side and removed the buttons at the bottom of blog and learn article pages.

Updated the following files:

/wp-content/themes/haleighs-hope/header.php
/wp-content/themes/haleighs-hope/single.php
/wp-content/themes/haleighs-hope/single-research.php

**Comment by bermanc76** [comment]
looks good.  closed.
