### ISSUE TITLE
Slow down the slideshow

### ISSUE THREAD

**Issue by keslavi** [keslavi/HHMedia#4]
Slowdown the slideshow. Or can you make it so you can click through the slides manually also?

-chris
"_The slideshow moves at the right speed I think.  But you can also move it manually by using the arrow buttons on your keyboard.  Perhaps we can add little arrows on the sides that users can click on with their cursor.  And we can also put the little white dots at the bottom so that the users knows that there are 5 slides rotating.  How does that sound?_"

**Comment by vinespn** [comment]
Previous and next arrow buttons have been added to allow user to manually click through the slides. Also, added little white dots at the bottom so that the users knows that there are 5 slides rotating.

**Comment by HCranford** [comment]
complete
