### ISSUE TITLE
Cannabinoids antioxidants and neuroprotectants slide

### ISSUE THREAD

**Issue by keslavi** [keslavi/HHMedia#5]
Cannabinoids antioxidants and neuroprotectants slide: New hemp picture and you can't read any of the white text

-chris
"_I think this is an old edit.  We already changed the picture and darkened the background so that the white writing stands out fine now.  Please confirm that this has been resolved to your satisfaction._"

**Comment by vinespn** [comment]
Cannabinoids antioxidants and neuroprotectants slide image has been updated already with darkened background.

**Comment by HCranford** [comment]
The background has been darkened, and the text is easier to read, but the image has not been changed. Jason has sent over several hemp field options to use instead. Please replace this image with one of his choices.

**Comment by keslavi** [comment]
Send Me the image to dev@e..... and I'll do it.

**Comment by bermanc76** [comment]
The image that is in place currently is one of the images that Jason sent over in an email on June 8th.  Please double-check and confirm that this actually needs to be replaced.

**Comment by bermanc76** [comment]
Jason has confirmed that the image is fine.  Can we please close this out?

**Comment by HCranford** [comment]
Complete, please close this ticket
