### ISSUE TITLE
Red Hands Slide

### ISSUE THREAD

**Issue by keslavi** [keslavi/HHMedia#6]
Red hands slide: Either zoom out so you can tell it’s a heart and maybe make the red paint on their hands not shiny at all. Or get a new picture. It looks like blood. Also, remove reference of medical conditions (Cancer, Crohns, Epilepsy, MS and many other ailments) and change medication to products. We cannot make medical claims.

**Comment by bermanc76** [comment]
The copy has been changed to remove the medical claims.  In regards to the image, it was a free image and there are no options available to zoom out.  In my personal opinion, I like the image.  I don't think it looks like blood.  Everyone knows the red hand logo for Haleigh's Hope and I think this image goes very well with it.  But it's up to you guys.  We'll have to source a different image if we want it changed.

**Comment by keslavi** [comment]
hcranford, can you comment on this further?

**Comment by HCranford** [comment]
Complete, please close this ticket
