### ISSUE TITLE
Change the Can Cannabis treat addiction thumbnail and picture

### ISSUE THREAD

**Issue by keslavi** [keslavi/HHMedia#7]
Change the Can Cannabis treat addiction thumbnail and picture

-Chris
"_Steve already changed the initial image.  We’ll make sure to only use family-friendly images moving forward.  However, Steve – the images that you chose are still not sized correctly for the both the thumbnail and article images.  It’s too large in both cases.  Are you able to resize it so that it matches the sizes constraints of all of the thumbnail and article images?_"

**Comment by vinespn** [comment]
"Can Cannabis Treat Addiction?" thumbnail and picture has been resized. Here's the image dimension - 676x378 pixels
