### ISSUE TITLE
blog emails to support@haleighshope.com

### ISSUE THREAD

**Issue by keslavi** [keslavi/HHMedia#8]
Redirect blog emails to support@haleighshope.com (Enter your email address below to have this information delivered directly to your inbox each week.)

-chris
"_The blog email entry is currently going to a Mail Chimp account.  From there, we can build out an email list to send a newsletter to customers.  My thoughts were that once we get everything else settled with the site, we start sending out a newsletter 1x per week.  The newsletter can have whatever we want in it but my recommendation would be that we send out a recap of a couple new articles that we added to the site that week (there will be 2-3 new ones each week) along with any other company news or special offers.  Is there reason that I’m not aware of why you want those emails to go to support?_"

**Comment by HCranford** [comment]
It is mandatory that blog emails go to support@haleighshope.com. We do not want them to filter through Mail Chimp

**Comment by keslavi** [comment]
If we are going to employ a newsletter we need to discuss this further; Jason was onboard with this but I understand potential security concerns.

**Comment by bermanc76** [comment]
The newsletter box has been removed from all Blog and Learn pages.  The newsletter sign up box at the bottom of the homepage has been replaced with copy encouraging users to Like us on FB.  Please verify this on the staging site: http://haleighshopeme.staging.wpengine.com/ and let Steve know if we can push the changes live and close this ticket out.

**Comment by HCranford** [comment]
Complete, please close this ticket
