### ISSUE TITLE
Add Cannabis as a Treatment for Multiple Sclerosis link to the More News column

### ISSUE THREAD

**Issue by keslavi** [keslavi/HHMedia#9]
Add Cannabis as a Treatment for Multiple Sclerosis link to the More News column located on the right side of the screens. With the others

**Comment by keslavi** [comment]
-chris 
"_The right-side column is set to only show the 5 most recent articles in that space.  More than that and it will lose its effectiveness.  Once we build out more content we’ll create a new home pages for the Learn section that will make it easier to access and find all the different articles._ "

**Comment by HCranford** [comment]
Complete, please close this ticket
